### PR TITLE
chore(sponsor): remove sponsor-related deprecated code

### PR DESCRIPTION
**Pull request by mattwang44**
## Types of changes

- [ ] **Bugfix**
- [ ] **New feature**
- [x] **Refactoring**
- [ ] **Breaking change** (any change that would cause existing functionality to not work as expected)
- [ ] **Documentation Update**
- [ ] **Other (please describe)**

## Description

remove deprecated sponsor-related code

Note that I only modified/deleted those templates and static from 2023 code.

### CODE REVIEW

**Comment by mattwang44** [comment]
@Ritabear please review the unit tests of sponsor API

**Comment by mattwang44** [comment]
@SivanYeh @erik1110 please join as the reviewer for the unit test part, thanks!

**Review by Ritabear — APPROVED** [review]

**Comment by mattwang44** [comment]
@erik1110 @SivanYeh any progress here?

**Comment by erik1110** [comment]
> @erik1110 @SivanYeh any progress here?
"I have set up the environment and am currently researching how to write test examples. I have left some questions in the discussion thread."

**Comment by SivanYeh** [comment]
> @erik1110 @SivanYeh any progress here?
@mattwang44 Same as Erik. Yet Josix may assigned it to other member because of the approaching due.
I would continue reading codes and asking.

**Comment by mattwang44** [comment]
will rebase again after #1132 is merged

**Comment by mattwang44** [comment]
Please let me know if this refactoring PR is either unwanted or still wanted. I wouldn't take any further action for now as it has been forgotten for quite a long time....

**Comment by SivanYeh** [comment]
@mattwang44  LGTM. I will resolve the conflix and create a new PR on src/templates/pycontw-2024 with similar redundancy

**Comment by mattwang44** [comment]
rebased

**Review by SivanYeh — APPROVED** [review]
LGTM!

**Pull request merged**
