### PR TITLE
deps: upgrade python to 3.10 and remove unused dependencies

### LINKED ISSUE #1028: [Feature Request] Upgrade Python to >3.6
## Describe the solution you'd like
Python 3.6 is going to EOL later this year (2021) https://endoflife.date/python This latest CI build shows we are currently supporting our site with 3.6 officially https://github.com/pycontw/pycon.tw/runs/2876830688 .

We may want to upgrade python after the main conference event.

## Describe alternatives you've considered
We may also consider to upgrade python after talk proposals are announced.

### PR DESCRIPTION
**Pull request by mattwang44**
## Types of changes

resolve #1028

Upgrade Python and organize packages

## Description

The currently-used [Python version (3.6) is already EOL](https://devguide.python.org/versions/), which also causes [GitHub dependabot to stop working on this repo](https://github.blog/changelog/2023-08-02-deprecation-notice-dependabot-to-drop-support-for-python-3-6-and-3-7/).

- Major: Upgrade python version to 3.10.14
  - update the version definitions
  - upgrade the packages that are incompatible with python 3.10
- Minor: remove unused packages

### CODE REVIEW

**Review by josix — APPROVED** [review]
LGTM

**Comment by mattwang44** [comment]
赫然發現目前用的 [Django 3.1 沒有支援 python 3.10](https://docs.djangoproject.com/en/5.0/releases/3.1/)，雖然我測試上沒遇到什麼問題，但麻煩請等後續升版 PR 都處理好之後再 deploy 到 staging

**Comment by josix** [comment]
大概只是因為當時還沒有 3.10

**Comment by SivanYeh** [comment]
LGTM!

**Pull request merged**
