### PR TITLE
Modify title style to be consistent

### PR DESCRIPTION
**Pull request by jp6ru8958958**
將每頁的標題風格改的更一致

## Types of changes
Please put an `x` in the box that applies

- [ ] **Bugfix**
- [ ] **New feature**
- [ ] **Refactoring**
- [ ] **Breaking change** (any change that would cause existing functionality to not work as expected)
- [ ] **Documentation Update**
- [x] **Other (improvement)**

## Description
原先的網站有某幾頁的標題和其他頁不相同的問題，例如"活動/Events"標籤底下的：
image
image
image

因此將其統一為
image
的樣式。

另外, 會議售票的部份則改為跟財務補助的風格一致。

### CODE REVIEW

**Comment by mattwang44** [comment]
following pages are not consistent:
- <host>/sponsor/prospectus/
- <host>/about/code-of-conduct/
- <host>/about/community/

**Comment by jp6ru8958958** [comment]
> following pages are not consistent:
> 
>     * /sponsor/prospectus/
> 
>     * /about/code-of-conduct/
> 
>     * /about/community

**Comment by jp6ru8958958** [comment]
好, 我馬上改, 剛剛貓不小心幫我按到close pr : )......

**Comment by yychen** [comment]
我覺得如果 keynote 用這種 h1 的話，好像要把 breadcrumb 拿掉比較合適...
然後有一頁很神祕的... 看你要不要讓他跟 events 的一致
/events/community-track/

**Pull request merged**
