### PR TITLE
Apply seo info for job-listings

### PR DESCRIPTION
**Pull request by tai271828**
## Types of changes

- [ ] **Bugfix**
- [x] **New feature**
- [ ] **Refactoring**
- [ ] **Breaking change** (any change that would cause existing functionality to not work as expected)
- [ ] **Documentation Update**
- [ ] **Other (please describe)**

## Description
Apply meta data for SEO according to Stacy's suggestion.

## Steps to Test This Pull Request
1. Check the job-listings page looks well.

## Expected behavior
Google ranking of this page is better.

### CODE REVIEW

**Comment by tai271828** [comment]
The meta information will be in the head section. For example a local testing site shows:

```
<head>

<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="description" content="">
<meta name="viewport" content="width=device-width, initial-scale=1">


<title>
【2020年Python工作職缺】Python知名企業職缺一覽表－PyCon Taiwan
 | PyCon Taiwan 2020</title>


<meta name="description" content="2020年Python熱門工作職缺、Python工程師職缺一覽表，PyCon Taiwan提供知名企業內部Python工程師職缺，直接查看所有知名品牌Python工作機會！" >
<meta name="keywords" content="Python職缺" >
<meta name="author" content="PyCon Taiwan" >
<meta name="copyright" content="本網頁著作權屬2020 PyCon Taiwan, All Rights Reserved " >
<meta name="application-name" content="2020年Python工作職缺">



<link rel="shortcut icon" href="/static/pycontw-2020/assets/favicon/favicon.ico">
<link rel="icon" type="image/png" href="/static/pycontw-2020/assets/favicon/favicon-16x16.png" sizes="16x16">
<link rel="icon" type="image/png" href="/static/pycontw-2020/assets/favicon/favicon-32x32.png" sizes="32x32">
<link rel="icon" type="image/png" href="/static/pycontw-2020/assets/favicon/favicon-192x192.png" sizes="192x192">


<meta property="og:type" content="website">
<meta property="og:title" content="【2020年Python熱門工作】Python知名企業職缺一覽表－PyCon Taiwan">
<meta property="og:description" content="2020年知名企業內部Python熱門工作職缺、Python工程師職缺一覽表，提供知名品牌企業內部Python工程師職缺、Python工作機會！">
<meta property="og:url" content="https://tw.pycon.org/2020/zh-hant/events/job-listings/">
<meta property="og:site_name" content="PyCon Taiwan">
<meta property="og:image" content="http://localhost:8000/static/pycontw-2020/assets/og-image.png">


<link rel="stylesheet" href="https://fonts.googleapis.com/earlyaccess/notosanstc.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Quicksand:300,400|Raleway:300,400|Philosopher|Quicksand&display=swap">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.css">

<link rel="stylesheet" href="/static/pycontw-2020/assets/twicon/twicon.css"><link rel="stylesheet" href="/static/CACHE/css/page.9f46e4a66d7c.css" type="text/css">






</head>
```

**Review by StacyYao — COMMENTED** [review]
可將"－PyCon Taiwan"刪掉喔(這是我當初給的語句，不是母版的)

**Comment by tai271828** [comment]
@StacyYao  Thanks for the suggestion. What do you think about the latest result:

```
<head>

<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="description" content="">
<meta name="viewport" content="width=device-width, initial-scale=1">


<title>【2020年Python工作職缺】Python知名企業職缺一覽表</title>


<meta name="description" content="2020年Python熱門工作職缺、Python工程師職缺一覽表，PyCon Taiwan提供知名企業內部Python工程師職缺，直接查看所有知名品牌Python工作機會！" >
<meta name="keywords" content="Python職缺" >
<meta name="author" content="PyCon Taiwan" >
<meta name="copyright" content="本網頁著作權屬2020 PyCon Taiwan, All Rights Reserved " >
<meta name="application-name" content="2020年Python工作職缺">



<link rel="shortcut icon" href="/static/pycontw-2020/assets/favicon/favicon.ico">
<link rel="icon" type="image/png" href="/static/pycontw-2020/assets/favicon/favicon-16x16.png" sizes="16x16">
<link rel="icon" type="image/png" href="/static/pycontw-2020/assets/favicon/favicon-32x32.png" sizes="32x32">
<link rel="icon" type="image/png" href="/static/pycontw-2020/assets/favicon/favicon-192x192.png" sizes="192x192">


<meta property="og:type" content="website">
<meta property="og:title" content="【2020年Python熱門工作】Python知名企業職缺一覽表－PyCon Taiwan">
<meta property="og:description" content="2020年知名企業內部Python熱門工作職缺、Python工程師職缺一覽表，提供知名品牌企業內部Python工程師職缺、Python工作機會！">
<meta property="og:url" content="https://tw.pycon.org/2020/zh-hant/events/job-listings/">
<meta property="og:site_name" content="PyCon Taiwan">
<meta property="og:image" content="http://localhost:8000/static/pycontw-2020/assets/og-image.png">


<link rel="stylesheet" href="https://fonts.googleapis.com/earlyaccess/notosanstc.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Quicksand:300,400|Raleway:300,400|Philosopher|Quicksand&display=swap">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.css">

<link rel="stylesheet" href="/static/pycontw-2020/assets/twicon/twicon.css"><link rel="stylesheet" href="/static/CACHE/css/page.f01b5250fd4d.css" type="text/css">






</head>
```

**Comment by StacyYao** [comment]
沒問題了喔~

**Comment by tai271828** [comment]
hi @yychen  , stacy has confirmed the meta information will help on SEO. May you please have a quick look if this change will make any regression against the other pages? If no, may you also please land the page for us? Thanks!

**Review by yychen — APPROVED** [review]
LGTM

**Pull request merged**
