### PR TITLE
contrib: rm unused fabfile

### PR DESCRIPTION
**Pull request by tai271828**
# Description
We are using docker technology to build and deploy our website. fabfiles are not used any more.

# Steps to Test This Pull Request
Follow `DEPLOY.md` to build and deploy the docker-based site.

# Expected behavior
The site is build in a docker and running.

### CODE REVIEW

**Comment by tai271828** [comment]
@JeremySungTw  would you please help us review my pull request?

**Comment by JeremySungTw** [comment]
Noted with thanks,
I will study the DEPLOY.md,
if i have any question i will leave you some messages.

**Comment by tai271828** [comment]
@JeremySungTw by review I meant "there is no regression after removing fabfile" or "we can't remove fabfile because ....". You don't need to implement a Dockerfile. Thanks.

**Comment by mattwang44** [comment]
though I know nothing about fabric, I guess `fabric3` in `requirements/travis.txt` should also be removed?

**Comment by mattwang44** [comment]
@tai271828 do you remember why this PR is closed without being merged?

**Comment by tai271828** [comment]
> @tai271828 do you remember why this PR is closed without being merged?

I barely remember, and it looks like a operation mistake. I might delete un-merged PR when I did house cleaning for my repository.

**Comment by tai271828** [comment]
Let me create an new one for the same propose. @mattwang44 may you please review (and merge) it for us?

**Pull request closed without merging**
