### PR TITLE
translation: rm compiled binary

### PR DESCRIPTION
**Pull request by tai271828**
From what I understand the mo files are compiled from the po files. I suppose the mo files will/should be generated during deployment, so we don't need to commit binaries into our repo.

I am not very familiar with django mo/po translation flow and our site deployment. Please correct me if I am wrong and feel free to ignore/reject this PR. Thanks.

### CODE REVIEW

**Comment by yychen** [comment]
Please refer to https://github.com/pycontw/pycon.tw#internationalisation and see if it suits you, or else you can directly use the `./manage.py compilemessages` to create the mo files if you have gettext installed.

Ping me if you don't have permission on transifex if you'd like to use it.

**Comment by yychen** [comment]
等等，我頭昏眼花了... 如果中英的 po 檔案都已經在 local 改好了就跟 transifex 無關了，compile always 在 local 做

**Comment by yychen** [comment]
OK. I got it all wrong. Yes, I'm gonna ignore this PR. No need to delete the mo. But please build the corresponding mo files according to the changes in https://github.com/pycontw/pycon.tw/pull/732

**Comment by tai271828** [comment]
If https://github.com/pycontw/pycon.tw/pull/734 is landed, we could/should also land this PR as well. : )

**Pull request merged**
